// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ai_indoor_nav_api.Data;

#nullable disable

namespace ai_indoor_nav_api.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250915213224_AddClosestNodeToPoi")]
    partial class AddClosestNodeToPoi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a minimal migration, so we don't need to rebuild the entire model
            // The model snapshot will be updated separately if needed
        }
    }
}